name: Add issues and PRs to Project

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_to_project:
    if: ${{ github.event_name == 'issues' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_TOKEN }}

